config/routes.rb
CfConsole::Application.routes.draw do
  # Prepend the locale at the beginning of each URL
  filter :locale

  # Default path
  root :to => "dashboard#index"

  # Dashboard
  get     'dashboard' => 'dashboard#index', :as => :dashboard

  # Applications
  get     'apps'                                    => 'apps#index',          :as => :apps_info
  post    'apps'                                    => 'apps#create',         :as => :apps_create
  get     'app/:name'                               => 'apps#show',           :as => :app_info
  delete  'app/:name'                               => 'apps#delete',         :as => :app_delete
  put     'app/:name/start'                         => 'apps#start',          :as => :app_start
  put     'app/:name/stop'                          => 'apps#stop',           :as => :app_stop
  put     'app/:name/restart'                       => 'apps#restart',        :as => :app_restart
  put     'app/:name/set_instances'                 => 'apps#set_instances',  :as => :app_set_instances
  put     'app/:name/set_memsize'                   => 'apps#set_memsize',    :as => :app_set_memsize
  put     'app/:name/set_var'                       => 'apps#set_var',        :as => :app_set_var
  put     'app/:name/unset_var'                     => 'apps#unset_var',      :as => :app_unset_var
  put     'app/:name/bind_service'                  => 'apps#bind_service',   :as => :app_bind_service
  put     'app/:name/unbind_service'                => 'apps#unbind_service', :as => :app_unbind_service
  put     'app/:name/map_url'                       => 'apps#map_url',        :as => :app_map_url
  put     'app/:name/unmap_url'                     => 'apps#unmap_url',      :as => :app_unmap_url
  put     'app/:name/update_bits'                   => 'apps#update_bits',    :as => :app_update_bits
  get     'app/:name/download_bits'                 => 'apps#download_bits',  :as => :app_download_bits
  get     'app/:name/files/:instance/:filename'     => 'apps#files',          :as => :app_files
  get     'app/:name/view_file/:instance/:filename' => 'apps#view_file',      :as => :app_view_file

  # Services
  get     'services'       => 'services#index',  :as => :services_info
  post    'services'       => 'services#create', :as => :service_create
  delete  'services/:name' => 'services#delete', :as => :service_delete

  # System Information
  get     'system' => 'system#index', :as => :system_info

  # Users
  get     'users'       => 'users#index',  :as => :users_info
  post    'users'       => 'users#create', :as => :user_create
  delete  'users/:name' => 'users#delete', :as => :user_delete
  
  get     'user/switch/:email'           => 'user#switch', :as => :user_switch, :constraints => { email: /[^\/]+/ }
  get     'user/switchapp/:email/:name'  => 'user#switch_view_app', :as => :user_switch_app, :constraints => { email: /[^\/]+/ }
  get     'user/clear'                   => 'user#clear', :as => :user_clear

  # Sessions
  get     'login'  => 'sessions#new',     :as => :login
  post    'login'  => 'sessions#create',  :as => :login
  get     'logout' => 'sessions#destroy', :as => :logout
end

app/models/service.rb
class Service
  def initialize(cf_client)
    @cf_client = cf_client
  end

  def find_all_services()
    @cf_client.list_services || []
  end

  def find(name)
    raise I18n.t('services.model.name_blank') if name.blank?
    @cf_client.service_info(name) || nil
  end

  def create(name, ss)
    raise I18n.t('services.model.name_blank') if name.blank?
    raise I18n.t('services.model.name_invalid', :name => name) if (name =~ /^[\w-]+$/).nil?
    raise I18n.t('services.model.ss_blank') if ss.blank?
    @cf_client.create_service(ss, name)
  end

  def delete(name)
    raise I18n.t('services.model.name_blank') if name.blank?
    @cf_client.delete_service(name)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    begin
      service = Service.new(@cf_client)
      @services = service.find_all_services()
      binded_apps = find_binded_apps()
      @services.collect {|service_item| service_item[:bindedapps] = binded_apps[service_item[:name]] ||= [] }
      @available_system_services = find_available_system_services()
    rescue Exception => ex
      flash[:alert] = ex.message
    end
  end

  def create
    @name = params[:name]
    @ss = params[:ss]
    if @name.blank?
      flash[:alert] = I18n.t('services.controller.name_blank')
    elsif @ss.blank?
      flash[:alert] = I18n.t('services.controller.service_blank')
    else
      begin
        @name = @name.strip.downcase
        @ss = @ss.strip
        service = Service.new(@cf_client)
        begin
          service_info = service.find(@name)
        rescue
          service_info = nil
        end
        if service_info.nil?
          service.create(@name, @ss)
          service_info = service.find(@name)
          @new_service = [] << service_info
          flash[:notice] = I18n.t('services.controller.service_created', :name => @name)
        else
          flash[:alert] = I18n.t('services.controller.already_exists')
        end
      rescue Exception => ex
        flash[:alert] = ex.message
      end
    end
    respond_to do |format|
      format.html { redirect_to services_info_url }
      format.js { flash.discard }
    end
  end

  def delete
    @name = params[:name]
    if @name.blank?
      flash[:alert] = I18n.t('services.controller.name_blank')
    else
      begin
        @name = @name.strip.downcase
        service = Service.new(@cf_client)
        service.delete(@name)
        flash[:notice] = I18n.t('services.controller.service_deleted', :name => @name)
      rescue Exception => ex
        flash[:alert] = ex.message
      end
    end
    respond_to do |format|
      format.html { redirect_to services_info_url }
      format.js { flash.discard }
    end
  end

  def find_binded_apps()
    bindedapps = {}
    app = App.new(@cf_client)
    apps = app.find_all_apps()
    apps.each do |app_item|
      next unless app_item[:services]
      app_item[:services].each do |service_item|
        bindedapps[service_item] ||= []
        bindedapps[service_item] << app_item[:name]
      end
    end
    bindedapps
  end

  def find_available_system_services
    available_system_services = []
    available_system_services << [I18n.t('services.controller.select_service'), ""]
    system = System.new(@cf_client)
    system_services = system.find_all_system_services()
    system_services.each do |service_type, service_value|
      service_value.each do |vendor, vendor_value|
        vendor_value.each do |version, service_info|
          available_system_services << [service_info[:vendor] + " " + service_info[:version], service_info[:vendor]]
        end
      end
    end
    available_system_services
  end
end

app/views/services/_service_item.html.haml
%tr.oddeven{:id => "service-" + service_item[:name]}
  %td= service_item[:name]
  %td= find_vendor_image(service_item[:vendor]).html_safe
  %td= service_item[:version]
  %td
    - if !service_item[:bindedapps].nil?
      - service_item[:bindedapps].each do |appname|
        = link_to appname, app_info_url(appname)
        %br/
  %td= Time.at(service_item[:meta][:created]).strftime(t('services.format.created'))
  %td= Time.at(service_item[:meta][:updated]).strftime(t('services.format.updated'))
  %td.tdcenter= link_to sprite_tag("delete", :title => t('services.delete_service'), :class => "delete icon-tip"),
                service_delete_url(service_item[:name]), :id => "delete-service-link", :remote => true,
                :method => :delete , :data => { :confirm => t('services.delete_service_confirm') }

app/views/services/_service_new.html.haml
.modalBox{:id => "add_service_modalBox"}
  = form_tag service_create_url, :id => "new-service-form", :remote => true do
    .modalBox-title=t('services.add_service')
    .modalBox-flash
    .modalBox-content
      %table
        %tbody
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('services.service_help_html'))
              = label_tag "service", t('services.service') + ":"
            %td
              = select_tag :ss, options_for_select(@available_system_services), :required => "required",
               :autofocus => "autofocus", :class => "service-chosen", :style => "width: 305px;"
              .form-field-error
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('services.name_help_html'))
              = label_tag "name",  t('services.name') + ":"
            %td
              = text_field_tag :name, @name, :size => 30, :required => "required", :pattern => "[a-zA-Z0-9-_]+",
                :placeholder => t('services.name_placeholder'), :title => t('services.name_title_html')
              .form-field-error
    .modalBox-submit= submit_tag t('services.add_service')

app/views/services/_services.html.haml
%table#services-table
  %thead
    %tr
      %th.thsort{:scope => "col"}= t('services.name_head')
      %th.thsort{:scope => "col"}= t('services.service_head')
      %th.thsort{:scope => "col"}= t('services.version_head')
      %th.thsort{:scope => "col"}= t('services.binded_apps_head')
      %th.thsort{:scope => "col"}= t('services.created_head')
      %th.thsort{:scope => "col"}= t('services.updated_head')
      %th.thcenter{:scope => "col", :width => "10%"}= t('services.actions_head')
  %tbody
    = render :partial => "service_item", :collection => @services

= render "service_new"

app/views/services/create.js.erb
$('#flash-content').empty();
$('.modalBox-flash').empty();
<%- if flash[:alert] %>
  request_processed = false;
  $('.modalBox-flash').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('.modalBox-flash').fadeIn('slow');
<%- else %>
  request_processed = true;
  var row = $('#services-table').append('<%= escape_javascript( render :partial => "service_item", :collection => @new_service ) %>').find('tr:last').addClass('highlight').hide();
  row.fadeIn(1800, function() { $(this).removeClass('highlight'); });
  servicesTable.dataTable().fnDestroy();
  servicesTable.dataTable(servicesTable_Settings);
<%- end %>

app/views/services/delete.js.erb
$('#flash-content').empty();
<%- if flash[:alert] %>
  $('#flash-content').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('#flash').fadeIn('slow');
<%- else %>
  var row = $('#service-<%= @name %>').html('<td colspan="7" class="tdcenter"><%= escape_javascript(flash[:notice]) %></td>').addClass('highlight');
  row.fadeOut(1800, function() { servicesTable.fnDeleteRow(row.get(0)); });
<%- end %>

app/views/services/index.html.haml
= title(t('services.title'))

.invoke-modalBox
%ul.tabs
  %li
    %a{:href => "#services"}
      = t('services.tab_services')

%div.panels
  %div.panel
    = render "services"