config/routes.rb
CfConsole::Application.routes.draw do
  # Prepend the locale at the beginning of each URL
  filter :locale

  # Default path
  root :to => "dashboard#index"

  # Dashboard
  get     'dashboard' => 'dashboard#index', :as => :dashboard

  # Applications
  get     'apps'                                    => 'apps#index',          :as => :apps_info
  post    'apps'                                    => 'apps#create',         :as => :apps_create
  get     'app/:name'                               => 'apps#show',           :as => :app_info
  delete  'app/:name'                               => 'apps#delete',         :as => :app_delete
  put     'app/:name/start'                         => 'apps#start',          :as => :app_start
  put     'app/:name/stop'                          => 'apps#stop',           :as => :app_stop
  put     'app/:name/restart'                       => 'apps#restart',        :as => :app_restart
  put     'app/:name/set_instances'                 => 'apps#set_instances',  :as => :app_set_instances
  put     'app/:name/set_memsize'                   => 'apps#set_memsize',    :as => :app_set_memsize
  put     'app/:name/set_var'                       => 'apps#set_var',        :as => :app_set_var
  put     'app/:name/unset_var'                     => 'apps#unset_var',      :as => :app_unset_var
  put     'app/:name/bind_service'                  => 'apps#bind_service',   :as => :app_bind_service
  put     'app/:name/unbind_service'                => 'apps#unbind_service', :as => :app_unbind_service
  put     'app/:name/map_url'                       => 'apps#map_url',        :as => :app_map_url
  put     'app/:name/unmap_url'                     => 'apps#unmap_url',      :as => :app_unmap_url
  put     'app/:name/update_bits'                   => 'apps#update_bits',    :as => :app_update_bits
  get     'app/:name/download_bits'                 => 'apps#download_bits',  :as => :app_download_bits
  get     'app/:name/files/:instance/:filename'     => 'apps#files',          :as => :app_files
  get     'app/:name/view_file/:instance/:filename' => 'apps#view_file',      :as => :app_view_file

  # Services
  get     'services'       => 'services#index',  :as => :services_info
  post    'services'       => 'services#create', :as => :service_create
  delete  'services/:name' => 'services#delete', :as => :service_delete

  # System Information
  get     'system' => 'system#index', :as => :system_info

  # Users
  get     'users'       => 'users#index',  :as => :users_info
  post    'users'       => 'users#create', :as => :user_create
  delete  'users/:name' => 'users#delete', :as => :user_delete
  
  get     'user/switch/:email'           => 'user#switch', :as => :user_switch, :constraints => { email: /[^\/]+/ }
  get     'user/switchapp/:email/:name'  => 'user#switch_view_app', :as => :user_switch_app, :constraints => { email: /[^\/]+/ }
  get     'user/clear'                   => 'user#clear', :as => :user_clear

  # Sessions
  get     'login'  => 'sessions#new',     :as => :login
  post    'login'  => 'sessions#create',  :as => :login
  get     'logout' => 'sessions#destroy', :as => :logout
end

app/models/user.rb
class User
  def initialize(cf_client)
    @cf_client = cf_client
  end

  def find_all_users()
    @cf_client.list_users || []
  end

  def find(username)
    raise I18n.t('users.model.email_blank') if username.blank?
    user_info = @cf_client.user_info(username) || nil
    # cc's prior to 31143c1 commit doesn't return the admin flag
    if !user_info.nil? && !user_info.has_key?(:admin)
      user_info = nil
      users = find_all_users()
      users.each do |user_item|
        if user_item[:email] == username
          user_info = user_item
          break
        end
      end
    end
    user_info
  end

  def is_admin?(username)
    user_info = find(username)
    return true if !user_info.nil? && user_info[:admin] == true
    false
  end

  def create(username, password)
    raise I18n.t('users.model.email_blank') if username.blank?
    raise I18n.t('users.model.password_blank') if password.blank?
    @cf_client.create_user(username, password)
  end

  def delete(username)
    raise I18n.t('users.model.email_blank') if username.blank?
    @cf_client.delete_user(username)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :require_admin

  def switch
    @email = params[:email]
    cookies[:cf_proxy_user] = @email
    redirect_to apps_info_url
  end
  
  def clear
    cookies.delete(:cf_proxy_user)
    redirect_to apps_info_url
  end
  
  def switch_view_app
    @email = params[:email]
    @name = params[:name]
    cookies[:cf_proxy_user] = @email
    redirect_to app_info_url(@name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin

  def index
    begin
      user = User.new(@cf_client)
      @users = user.find_all_users()
    rescue Exception => ex
      flash[:alert] = ex.message
    end
  end

  def create
    @email = params[:email]
    @password = params[:password]
    @vpassword = params[:vpassword]
    if @email.blank?
      flash[:alert] = I18n.t('users.controller.email_blank')
    elsif @password.blank?
      flash[:alert] = I18n.t('users.controller.password_blank')
    elsif @password != @vpassword
      flash[:alert] = I18n.t('users.controller.passwords_match')
    else
      begin
        @email = @email.strip.downcase
        @password = @password.strip
        user = User.new(@cf_client)
        begin
          user_info = user.find(@email)
        rescue
          user_info = nil
        end
        if user_info.nil?
          user.create(@email, @password)
          user_info = user.find(@email)
          @new_user = [] << user_info
          flash[:notice] = I18n.t('users.controller.user_created', :email => @email)
        else
          flash[:alert] = I18n.t('users.controller.already_exists')
        end
      rescue Exception => ex
        flash[:alert] = ex.message
      end
    end
    respond_to do |format|
      format.html { redirect_to users_info_url }
      format.js { flash.discard }
    end
  end

  def delete
    @email = params[:name]
    if @email.blank?
      flash[:alert] = I18n.t('users.controller.email_blank')
    else
      begin
        @email = Base64.decode64(@email)
        user = User.new(@cf_client)
        user.delete(@email)
        flash[:notice] = I18n.t('users.controller.user_deleted', :email => @email)
      rescue Exception => ex
        flash[:alert] = ex.message
      end
    end
    respond_to do |format|
      format.html { redirect_to users_info_url }
      format.js { flash.discard }
    end
  end
end

app/views/users/_user_item.html.haml
%tr.oddeven{:id => "user-" + user_item[:email].hash.to_s}
  %td= link_to user_item[:email], user_switch_url(Rack::Utils.escape(user_item[:email]))
  %td
    - if !user_item[:apps].nil?
      - user_item[:apps].each do |appname|
        = link_to appname[:name], user_switch_app_url(Rack::Utils.escape(user_item[:email]), appname[:name])
        %br/
  %td.tdcenter
    - if user_item[:admin]
      = sprite_tag("ok", :alt => t('users.admin'))
  %td.tdcenter= link_to sprite_tag("delete", :title => t('users.delete_user'), :class => "delete icon-tip"),
                user_delete_url(Base64.encode64(user_item[:email])), :id => "delete-user-link", :remote => true,
                :method => :delete, :data => { :confirm => t('users.delete_user_confirm') }

app/views/users/_user_new.html.haml
.modalBox{:id => "add_user_modalBox"}
  = form_tag user_create_url, :id => "new-user-form", :remote => true do
    .modalBox-title
      = t('users.add_user')
    .modalBox-flash
    .modalBox-content
      %table
        %tbody
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('users.email_help_html'))
              = label_tag "email", t('users.email') + ":"
            %td
              = email_field_tag :email, @email, :size => 50, :required => "required", :autofocus => "autofocus",
                :placeholder => t('users.email_placeholder')
              .form-field-error
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('users.password_help_html'))
              = label_tag "password", t('users.password') + ":"
            %td
              = password_field_tag :password, nil, :size => 50, :required => "required",
                :placeholder => t('users.password_placeholder')
              .form-field-error
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('users.vpassword_help_html'))
              = label_tag "vpassword", t('users.vpassword') + ":"
            %td
              = password_field_tag :vpassword, nil, :size => 50, :required => "required",
                :data_equals => "password", :data_equals_label => t('users.password'),
                :placeholder => t('users.vpassword_placeholder')
              .form-field-error
    .modalBox-submit= submit_tag t('users.add_user')

app/views/users/_users.html.haml
%table#users-table
  %thead
    %tr
      %th.thsort{:scope => "col"}
        = t('users.email_head')
      %th.thsort{:scope => "col"}
        = t('users.applications_head')
      %th.thsort{:scope => "col", :width => "15%"}
        = t('users.admin_head')
      %th.thcenter{:scope => "col", :width => "10%"}
        = t('users.actions_head')
  %tbody
    = render :partial => "user_item", :collection => @users

= render "user_new"

app/views/users/create.js.erb
$('#flash-content').empty();
$('.modalBox-flash').empty();
<%- if flash[:alert] %>
  request_processed = false;
  $('.modalBox-flash').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('.modalBox-flash').fadeIn('slow');
<%- else %>
  request_processed = true;
  var row = $('#users-table').append('<%= escape_javascript( render :partial => "user_item", :collection => @new_user ) %>').find('tr:last').addClass('highlight').hide();
  row.fadeIn(1800, function() { $(this).removeClass('highlight'); });
  usersTable.dataTable().fnDestroy();
  usersTable.dataTable(usersTable_Settings);
<%- end %>

app/views/users/delete.js.erb
$('#flash-content').empty();
<%- if flash[:alert] %>
  $('#flash-content').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('#flash').fadeIn('slow');
<%- else %>
  var row = $('#user-<%= @email.hash.to_s %>').html('<td colspan="4" class="tdcenter"><%= escape_javascript(flash[:notice]) %></td>').addClass('highlight');
  row.fadeOut(1800, function() { usersTable.fnDeleteRow(row.get(0)); });
<%- end %>

app/views/users/index.html.haml
= title(t('users.title'))

.invoke-modalBox
%ul.tabs
  %li
    %a{:href => "#users"}
      = t('users.tab_users')

%div.panels
  %div.panel
    = render "users"