config/routes.rb
CfConsole::Application.routes.draw do
  # Prepend the locale at the beginning of each URL
  filter :locale

  # Default path
  root :to => "dashboard#index"

  # Dashboard
  get     'dashboard' => 'dashboard#index', :as => :dashboard

  # Applications
  get     'apps'                                    => 'apps#index',          :as => :apps_info
  post    'apps'                                    => 'apps#create',         :as => :apps_create
  get     'app/:name'                               => 'apps#show',           :as => :app_info
  delete  'app/:name'                               => 'apps#delete',         :as => :app_delete
  put     'app/:name/start'                         => 'apps#start',          :as => :app_start
  put     'app/:name/stop'                          => 'apps#stop',           :as => :app_stop
  put     'app/:name/restart'                       => 'apps#restart',        :as => :app_restart
  put     'app/:name/set_instances'                 => 'apps#set_instances',  :as => :app_set_instances
  put     'app/:name/set_memsize'                   => 'apps#set_memsize',    :as => :app_set_memsize
  put     'app/:name/set_var'                       => 'apps#set_var',        :as => :app_set_var
  put     'app/:name/unset_var'                     => 'apps#unset_var',      :as => :app_unset_var
  put     'app/:name/bind_service'                  => 'apps#bind_service',   :as => :app_bind_service
  put     'app/:name/unbind_service'                => 'apps#unbind_service', :as => :app_unbind_service
  put     'app/:name/map_url'                       => 'apps#map_url',        :as => :app_map_url
  put     'app/:name/unmap_url'                     => 'apps#unmap_url',      :as => :app_unmap_url
  put     'app/:name/update_bits'                   => 'apps#update_bits',    :as => :app_update_bits
  get     'app/:name/download_bits'                 => 'apps#download_bits',  :as => :app_download_bits
  get     'app/:name/files/:instance/:filename'     => 'apps#files',          :as => :app_files
  get     'app/:name/view_file/:instance/:filename' => 'apps#view_file',      :as => :app_view_file

  # Services
  get     'services'       => 'services#index',  :as => :services_info
  post    'services'       => 'services#create', :as => :service_create
  delete  'services/:name' => 'services#delete', :as => :service_delete

  # System Information
  get     'system' => 'system#index', :as => :system_info

  # Users
  get     'users'       => 'users#index',  :as => :users_info
  post    'users'       => 'users#create', :as => :user_create
  delete  'users/:name' => 'users#delete', :as => :user_delete
  
  get     'user/switch/:email'           => 'user#switch', :as => :user_switch, :constraints => { email: /[^\/]+/ }
  get     'user/switchapp/:email/:name'  => 'user#switch_view_app', :as => :user_switch_app, :constraints => { email: /[^\/]+/ }
  get     'user/clear'                   => 'user#clear', :as => :user_clear

  # Sessions
  get     'login'  => 'sessions#new',     :as => :login
  post    'login'  => 'sessions#create',  :as => :login
  get     'logout' => 'sessions#destroy', :as => :logout
end

app/views/apps/files/_app_file_item.html.haml
%tr.oddeven{:id => "app-" + @name + "-files-" + app_file_item[:name]}
  %td
    - if app_file_item[:type] == "dir"
      = sprite_tag("dir")
      = link_to app_file_item[:name], app_files_url(@name, 0, Base64.encode64(app_file_item[:path] + app_file_item[:name])), :remote => :true
    - else
      = sprite_tag("file")
      = link_to app_file_item[:name], app_view_file_url(@name, 0, Base64.encode64(app_file_item[:path] + app_file_item[:name]), :formatcode => true), :remote => :true
  %td.tdright= app_file_item[:size]

app/views/apps/files/_app_files.html.haml
#app-files
  #app-files-breadcrumbs
    %b
      = link_to @name, app_files_url(@name, 0, Base64.encode64("/")), :remote => :true
    - if @filename && !@filename.empty? && @filename != "/"
      - path = ""
      - dirname = File.dirname(@filename)
      - dirname.split("/").each do |dir|
        - if !dir.empty?
          - path = File.join(path, dir)
          \/
          = link_to dir, app_files_url(@name, 0, Base64.encode64(File.join(path, "/"))), :remote => :true
      \/ #{File.basename(@filename)}
      - if @file_loc
        %small
          (#{@file_loc} sloc)

  #app-files-contents
    - if @app_files
      %table#app-files-table
        %thead
          %tr
            %th{:scope => "col"}=t('apps.files.name_head')
            %th.tdright{:scope => "col", :width => "10%"}=t('apps.files.size_head')
        %tbody
          - if @filename && !@filename.empty? && @filename != "/"
            %tr.oddeven
              %td
                = sprite_tag("dir")
                = link_to "..", app_files_url(@name, 0, Base64.encode64(File.join(File.dirname(@filename), "/"))), :remote => :true
              %td.tdright -
          - @app_files.select{ |file| file[:type] == "dir"}.each do |dir_item|
            = render :partial => "apps/files/app_file_item", :object => dir_item
          - @app_files.select{ |file| file[:type] == "file"}.each do |file_item|
            = render :partial => "apps/files/app_file_item", :object => file_item
    - if @file_contents
      = @file_contents.html_safe

- content_for :javascripts do
  :javascript
    $(function() {
      app_download_bits_url = '#{app_download_bits_url}';
    });

app/views/apps/files/app_view_file.html.haml
.modalLog-title=t('apps.files.log_title', :filename => @filename, :instance => @instance, :name => @name)
.modalLog-flash
.modalLog-content
  %table#app-logfile-table
    %thead
      %tr
        %th=t('apps.files.log_head')
    %tbody
      - if !@file_contents.nil?
        - @file_contents.each do |row|
          %tr
            %td= row

- if flash[:alert]
  :javascript
    $(function() {
      $('#flash-content').empty();
      $('.modalLog-flash').empty();
      $('.modalLog-flash').append('<div class="alert">#{escape_javascript(flash[:alert])}</div>');
      $('.modalLog-flash').fadeIn('slow');
    });
- else
  :javascript
    $(function() {
      $('#flash-content').empty();
      $('.modalLog-flash').empty();
      appLogfileTable_Settings = {
        'bAutoWidth':      false,
        'bProcessing':     true,
        'bFilter':         true,
        'bLengthChange':   false,
        'bSort':           false,
        'bStateSave':      false,
        'iDisplayLength':  20,
        'oLanguage':       dataTables_lang,
        'sPaginationType': 'full_numbers'
      };
      appLogfileTable = $('table#app-logfile-table').dataTable(appLogfileTable_Settings);
    });

app/views/apps/files/files.js.erb
$('#flash-content').empty();
<%- if flash[:alert] %>
  $('#flash-content').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('#flash').fadeIn('slow');
<%- else %>
  $('#app-files').hide(150, function() {
    $('#app-files').replaceWith('<%= escape_javascript(render "apps/files/app_files", :collection => @app_files) %>');
    $('#app-files').show(150);
  });
<%- end %>

app/views/apps/files/view_file.js.erb
$('#flash-content').empty();
<%- if flash[:alert] %>
  $('#flash-content').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('#flash').fadeIn('slow');
<%- else %>
  $('#app-files').hide(150, function() {
    $('#app-files').replaceWith('<%= escape_javascript(render "apps/files/app_files", :locals => {:file_contents => @file_contents}) %>');
    $('#app-files').show(150);
  });
<%- end %>