config/routes.rb
CfConsole::Application.routes.draw do
  # Prepend the locale at the beginning of each URL
  filter :locale

  # Default path
  root :to => "dashboard#index"

  # Dashboard
  get     'dashboard' => 'dashboard#index', :as => :dashboard

  # Applications
  get     'apps'                                    => 'apps#index',          :as => :apps_info
  post    'apps'                                    => 'apps#create',         :as => :apps_create
  get     'app/:name'                               => 'apps#show',           :as => :app_info
  delete  'app/:name'                               => 'apps#delete',         :as => :app_delete
  put     'app/:name/start'                         => 'apps#start',          :as => :app_start
  put     'app/:name/stop'                          => 'apps#stop',           :as => :app_stop
  put     'app/:name/restart'                       => 'apps#restart',        :as => :app_restart
  put     'app/:name/set_instances'                 => 'apps#set_instances',  :as => :app_set_instances
  put     'app/:name/set_memsize'                   => 'apps#set_memsize',    :as => :app_set_memsize
  put     'app/:name/set_var'                       => 'apps#set_var',        :as => :app_set_var
  put     'app/:name/unset_var'                     => 'apps#unset_var',      :as => :app_unset_var
  put     'app/:name/bind_service'                  => 'apps#bind_service',   :as => :app_bind_service
  put     'app/:name/unbind_service'                => 'apps#unbind_service', :as => :app_unbind_service
  put     'app/:name/map_url'                       => 'apps#map_url',        :as => :app_map_url
  put     'app/:name/unmap_url'                     => 'apps#unmap_url',      :as => :app_unmap_url
  put     'app/:name/update_bits'                   => 'apps#update_bits',    :as => :app_update_bits
  get     'app/:name/download_bits'                 => 'apps#download_bits',  :as => :app_download_bits
  get     'app/:name/files/:instance/:filename'     => 'apps#files',          :as => :app_files
  get     'app/:name/view_file/:instance/:filename' => 'apps#view_file',      :as => :app_view_file

  # Services
  get     'services'       => 'services#index',  :as => :services_info
  post    'services'       => 'services#create', :as => :service_create
  delete  'services/:name' => 'services#delete', :as => :service_delete

  # System Information
  get     'system' => 'system#index', :as => :system_info

  # Users
  get     'users'       => 'users#index',  :as => :users_info
  post    'users'       => 'users#create', :as => :user_create
  delete  'users/:name' => 'users#delete', :as => :user_delete
  
  get     'user/switch/:email'           => 'user#switch', :as => :user_switch, :constraints => { email: /[^\/]+/ }
  get     'user/switchapp/:email/:name'  => 'user#switch_view_app', :as => :user_switch_app, :constraints => { email: /[^\/]+/ }
  get     'user/clear'                   => 'user#clear', :as => :user_clear

  # Sessions
  get     'login'  => 'sessions#new',     :as => :login
  post    'login'  => 'sessions#create',  :as => :login
  get     'logout' => 'sessions#destroy', :as => :logout
end

app/views/apps/_app_item.html.haml
%tr.oddeven{:id => "app-" + app_item[:name]}
  %td= link_to app_item[:name], app_info_url(app_item[:name])
  %td
    %span{:id => "app-" + app_item[:name] + "-tooltip"}= health(app_item).html_safe
    %div.tooltip{:id => "app-" + app_item[:name] + "-tooltipbox"}
      %table
        %thead
          %tr
            %th.thcenter{:scope => "col"}=t('apps.state_head')
            %th.thcenter{:scope => "col"}=t('apps.instances_head')
        %tbody
          - app_item[:instances_states].each do |instances_states_item|
            %tr
              %td.tdcenter
                %span{:style => "color: #{instances_states_item[:color]}"}= instances_states_item[:label]
              %td.tdcenter= instances_states_item[:data]
  %td= app_item[:instances]
  %td= pretty_size(app_item[:resources][:memory] * 1024 * 1024, 0)
  %td= pretty_size(app_item[:resources][:disk] * 1024 * 1024, 0)
  %td= find_vendor_image(app_item[:staging][:model]).html_safe
  %td= find_vendor_image(app_item[:staging][:stack]).html_safe
  %td
    - app_item[:services].each do |service_name|
      = find_vendor_image(service_name).html_safe
      %br/
  %td.tdcenter
    - if app_item[:state] == "STARTED"
      = link_to sprite_tag("restart", :title => t('apps.restart_app'), :class => "restart icon-tip"),
        app_restart_url(app_item[:name]), :id => "restart-app-link", :method => :put, :remote => true
      = link_to sprite_tag("stop", :title => t('apps.stop_app'), :class => "stop icon-tip"),
        app_stop_url(app_item[:name]), :id => "stop-app-link", :method => :put, :remote => true
    - else
      = link_to sprite_tag("start", :title => t('apps.start_app'), :class => "start icon-tip"),
        app_start_url(app_item[:name]), :id => "start-app-link", :method => :put, :remote => true
    - if git_deploy_available?
      = link_to sprite_tag("update-bits", :title => t('apps.upload_bits'), :class => "update-bits icon-tip"),
        app_update_bits_url(app_item[:name]), :rel => "#update_application_bits_modalBox", :class => "uploadAppBits"
    = link_to sprite_tag("delete", :title => t('apps.delete_app'), :class => "delete icon-tip"),
      app_delete_url(app_item[:name]), :id => "delete-app-link", :remote => true,
      :method => :delete, :data => { :confirm => t('apps.delete_app_confirm') }

app/views/apps/_app_new.html.haml
.modalBox{:id => "create_application_modalBox"}
  = form_tag apps_create_url, :id => "new-app-form", :remote => true do
    .modalBox-title=t('apps.add_app')
    .modalBox-flash
    .modalBox-content
      %table
        %tbody
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.name_help_html'))
              = label_tag "name", t('apps.name') + ":"
            %td
              = text_field_tag :name, @name, :size => 50, :required => "required", :autofocus => "autofocus",
                :placeholder => t('apps.name_placeholder'), :pattern => "[a-zA-Z0-9-_]+", :title => t('apps.name_title_html')
              .form-field-error
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.instances_num_help_html'))
              = label_tag "instances", t('apps.instances_num') + ":"
            %td
              = number_field_tag :instances, @instances, :min => 1, :max => @available_instances, :required => "required"
              .form-field-error
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.memory_size_help_html'))
              = label_tag "memsize", t('apps.memory_size') + ":"
            %td
              = select_tag :memsize, options_for_select(@available_memsizes), :required => "required",
                :class => "memory-chosen", :style => "width: 100px;"
              .form-field-error
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.type_help_html'))
              = label_tag "type", t('apps.type') + ":"
            %td
              = select_tag :type, options_for_select(@available_frameworks), :required => "required",
                :class => "type-chosen", :style => "width: 300px;"
              .form-field-error
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.url_help_html'))
              = label_tag "url", t('apps.url') + ":"
            %td
              = url_field_tag :url, @url, :size => 50, :required => "required", :placeholder => t('apps.url_placeholder')
              .form-field-error
    .modalBox-title=t('apps.optional_data')
    .modalBox-content
      %table
        %tbody
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.bind_service_help_html'))
              = label_tag "service", t('apps.bind_service') + ":"
            %td
              = select_tag :service, options_for_select(@available_services), :class => "service-chosen", :style => "width: 300px;"
              .form-field-error
          - if git_deploy_available?
            %tr
              %td
                = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.deploy_from_help_html'))
                = label_tag "deployfrom", t('apps.deploy_from') + ":"
              %td
                = radio_button_tag :deployfrom, 'git', true, :disabled => true
                = t('apps.git')
            %tr
              %td
                = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.git_repo_help_html'))
                = label_tag "gitrepo", t('apps.git_repo') + ":"
              %td
                = text_field_tag :gitrepo, @gitrepo, :size => 50, :placeholder => t('apps.git_repo_placeholder'),
                  :pattern => "(git://[a-z0-9]+([-.]{1}[a-z0-9]+)*.[a-z]{2,5}(([0-9]{1,5})?.*)?.git)?",
                  :title => t('apps.git_repo_title_html')
                .form-field-error
            %tr
              %td
                = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.git_branch_help_html'))
                = label_tag "gitrepo", t('apps.git_branch') + ":"
              %td
                = text_field_tag :gitbranch, @gitbranch, :size => 20, :placeholder => t('apps.git_branch_placeholder')
                .form-field-error
    .modalBox-submit= submit_tag t('apps.add_app')

- if @newapp_default_urldomain
  - content_for :javascripts do
    :javascript
      $(function() {
        $(document)
          .on('focus', '#new-app-form input#url', function() {
            if ($(this).val() == "") {
              var app_name = $('#new-app-form input#name');
              $(this).val('http://' + app_name.val() + '.#{@newapp_default_urldomain}');
            }
          });
      });

app/views/apps/_app_upload_bits.html.haml
.modalBox{:id => "update_application_bits_modalBox"}
  = form_tag "#", :id => "upload-app-bits-form", :method => :put, :remote => true do
    .modalBox-title=t('apps.upload_bits')
    .modalBox-flash
    .modalBox-content
      %table
        %tbody
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.deploy_from_help_html'))
              = label_tag "deployfrom", t('apps.deploy_from') + ":"
            %td
              = radio_button_tag :deployfrom, 'git', true, :disabled => true
              = t('apps.git')
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.git_repo_help_html'))
              = label_tag "gitrepo", t('apps.git_repo') + ":"
            %td
              = text_field_tag :gitrepo, @gitrepo, :size => 50, :required => "required", :autofocus => "autofocus",
                :placeholder => t('apps.git_repo_placeholder'),
                :pattern => "git://[a-z0-9]+([-.]{1}[a-z0-9]+)*.[a-z]{2,5}(([0-9]{1,5})?.*)?.git",
                :title => t('apps.git_repo_title_html')
              .form-field-error
          %tr
            %td
              = sprite_tag("help", :alt => "?", :class=> "help", :title => t('apps.git_branch_help_html'))
              = label_tag "gitrepo", t('apps.git_branch') + ":"
            %td
              = text_field_tag :gitbranch, @gitbranch, :size => 20, :placeholder => t('apps.git_branch_placeholder')
              .form-field-error
    .modalBox-submit= submit_tag t('apps.upload_bits')

app/views/apps/_apps.html.haml
%table#apps-table
  %thead
    %tr
      %th.thsort{:scope => "col", :rowspan => 2}=t('apps.application_head')
      %th.thsort{:scope => "col", :rowspan => 2}=t('apps.health_head')
      %th.thcenter{:scope => "col", :colspan => 6}=t('apps.resources_head')
      %th.thcenter{:scope => "col", :rowspan => 2, :width => "12%"}=t('apps.actions_head')
    %tr
      %th.thsort{:scope => "col"}=t('apps.instances_head')
      %th.thsort{:scope => "col"}=t('apps.memory_head')
      %th.thsort{:scope => "col"}=t('apps.disk_head')
      %th.thsort{:scope => "col"}=t('apps.framework_head')
      %th.thsort{:scope => "col"}=t('apps.runtime_head')
      %th.thsort{:scope => "col"}=t('apps.services_head')
  %tbody
    = render :partial => "app_item", :collection => @apps

= render "app_new"
= render "app_upload_bits"

app/views/apps/create.js.erb
$('#flash-content').empty();
$('.modalBox-flash').empty();
<%- if flash[:alert] %>
  request_processed = false;
  $('.modalBox-flash').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('.modalBox-flash').fadeIn('slow');
<%- else %>
  request_processed = true;
  var row = $('#apps-table').append('<%= escape_javascript(render :partial => "app_item", :collection => @new_app) %>').find('tr:last').addClass('highlight').hide();
  row.fadeIn(1800, function() { $(this).removeClass('highlight'); });
  appsTable.dataTable().fnDestroy();
  appsTable.dataTable(appsTable_Settings);
  <%- if flash[:notice] %>
    $('#flash-content').append('<div class="notice"><%= escape_javascript(flash[:notice]) %></div>');
    $('#flash').fadeIn('slow');
  <%- end %>
<%- end %>

app/views/apps/delete.js.erb
$('#flash-content').empty();
<%- if flash[:alert] %>
  $('#flash-content').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('#flash').fadeIn('slow');
<%- else %>
  var row = $('#app-<%= @name %>').html('<td colspan="9" class="tdcenter"><%= escape_javascript(flash[:notice]) %></td>').addClass('highlight');
  row.fadeOut(1800, function() { appsTable.fnDeleteRow(row.get(0)); });
<%- end %>

app/views/apps/index.html.haml
= title(t('apps.title'))

.invoke-modalBox
%ul.tabs
  %li
    %a{:href => "#apps"}
      = t('apps.tab_apps')

%div.panels
  %div.panel
    = render "apps"

app/views/apps/restart.js.erb
$('#flash-content').empty();
<%- if flash[:alert] %>
  request_processed = false;
  $('#flash-content').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('#flash').fadeIn('slow');
<%- else %>
  request_processed = true;
  appsTable.fnDeleteRow($('#app-<%= @name %>').get(0));
  var row = $('#apps-table').append('<%= escape_javascript( render :partial => "apps/app_item", :collection => @updated_app ) %>');
  appsTable.dataTable().fnDestroy();
  appsTable.dataTable(appsTable_Settings);
<%- end %>

app/views/apps/show.html.haml
= title(t('apps.title_app', :name => @name))

.invoke-modalBox
%ul.tabs
  %li
    %a{:href => "#resources"}
      = t('apps.tab_resources')
  %li
    %a{:href => "#instances"}
      = t('apps.tab_instances')
  %li
    %a{:href => "#crashes"}
      = t('apps.tab_crashes')
  %li
    %a{:href => "#envvars"}
      = t('apps.tab_envvars')
  %li
    %a{:href => "#services"}
      = t('apps.tab_services')
  %li
    %a{:href => "#urls"}
      = t('apps.tab_urls')
  %li
    %a{:href => "#files"}
      = t('apps.tab_files')

%div.panels
  %div.panel
    = render "apps/resources/app_resources"
  %div.panel
    = render "apps/instances/app_instances"
  %div.panel
    = render "apps/crashes/app_crashes"
  %div.panel
    = render "apps/envvars/app_envvars"
  %div.panel
    = render "apps/services/app_services"
  %div.panel
    = render "apps/urls/app_urls"
  %div.panel
    = render "apps/files/app_files"

app/views/apps/start.js.erb
$('#flash-content').empty();
<%- if flash[:alert] %>
  request_processed = false;
  $('#flash-content').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('#flash').fadeIn('slow');
<%- else %>
  request_processed = true;
  appsTable.fnDeleteRow($('#app-<%= @name %>').get(0));
  var row = $('#apps-table').append('<%= escape_javascript( render :partial => "apps/app_item", :collection => @updated_app ) %>');
  appsTable.dataTable().fnDestroy();
  appsTable.dataTable(appsTable_Settings);
<%- end %>

app/views/apps/stop.js.erb
$('#flash-content').empty();
<%- if flash[:alert] %>
  request_processed = false;
  $('#flash-content').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('#flash').fadeIn('slow');
<%- else %>
  request_processed = true;
  appsTable.fnDeleteRow($('#app-<%= @name %>').get(0));
  var row = $('#apps-table').append('<%= escape_javascript( render :partial => "apps/app_item", :collection => @updated_app ) %>');
  appsTable.dataTable().fnDestroy();
  appsTable.dataTable(appsTable_Settings);
<%- end %>

app/views/apps/update_bits.js.erb
$('#flash-content').empty();
$('.modalBox-flash').empty();
<%- if flash[:alert] %>
  request_processed = false;
  $('.modalBox-flash').append('<div class="alert"><%= escape_javascript(flash[:alert]) %></div>');
  $('.modalBox-flash').fadeIn('slow');
<%- else %>
  request_processed = true;
  <%- if flash[:notice] %>
    $('#flash-content').append('<div class="notice"><%= escape_javascript(flash[:notice]) %></div>');
    $('#flash').fadeIn('slow');
  <%- end %>
<%- end %>